#!/usr/bin/env python3
import zmq
import random
import sys
import time

port = "5556"
if len(sys.argv) > 1:
    port =  sys.argv[1]
    int(port)

context = zmq.Context()
socket = context.socket(zmq.PUB)
socket.bind("tcp://*:%s" % port)

while True:
    # topic = random.randrange(9999,10005)
    # messagedata = random.randrange(1,215) - 80
    # print("%d %d" % (topic, messagedata))
    topic = "jtest"
    messagedata = "jtestmsg"
    print("%s %s" % (topic, messagedata))

    # socket.send("%d %d" % (topic, messagedata))
    # socket.send("%d %d" % (topic.encode('ascii'), messagedata.encode('ascii')))
    # socket.send("%d %d" % (topic.encode('bytes'), messagedata.encode('bytes')))
    # socket.send("%s %s" % (f"{topic}", f"{messagedata}"))
    socket.send_string("%s %s" % (f"{topic}", f"{messagedata}"))
    time.sleep(5)
